### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by genofuzzy** [visallo/visallo#1219]
Hello,

I'm trying to packaging with IntelliJ, but I encountered some test failures in visallo-model-vertexium-test:

Tests in error: 
  InMemoryOntologyRepositoryTest>OntologyRepositoryTestBase.testGettingParentConceptReturnsParentProperties:56->OntologyRepositoryTestBase.loadHierarchyOwlFile:253->OntologyRepositoryTestBase.createTestOntologyRepository:257 » IllegalArgument
  InMemoryOntologyRepositoryTest>OntologyRepositoryTestBase.changingDisplayAnnotationsShouldSucceed:44->OntologyRepositoryTestBase.loadTestOwlFile:245->OntologyRepositoryTestBase.createTestOntologyRepository:257 » IllegalArgument
  InMemoryOntologyRepositoryTest>OntologyRepositoryTestBase.dependenciesBetweenOntologyFilesShouldNotChangeParentProperties:64->OntologyRepositoryTestBase.loadTestOwlFile:245->OntologyRepositoryTestBase.createTestOntologyRepository:257 » IllegalArgument
  VertexiumOntologyRepositoryTest>OntologyRepositoryTestBase.testGettingParentConceptReturnsParentProperties:56->OntologyRepositoryTestBase.loadHierarchyOwlFile:253->OntologyRepositoryTestBase.createTestOntologyRepository:257 » IllegalArgument
  VertexiumOntologyRepositoryTest>OntologyRepositoryTestBase.changingDisplayAnnotationsShouldSucceed:44->OntologyRepositoryTestBase.loadTestOwlFile:245->OntologyRepositoryTestBase.createTestOntologyRepository:257 » IllegalArgument
  VertexiumOntologyRepositoryTest>OntologyRepositoryTestBase.dependenciesBetweenOntologyFilesShouldNotChangeParentProperties:64->OntologyRepositoryTestBase.loadTestOwlFile:245->OntologyRepositoryTestBase.createTestOntologyRepository:257 » IllegalArgument

Tests run: 118, Failures: 0, Errors: 6, Skipped: 0 

If I comment that test everything goes well. I didn't try to go deeper why the test fails.

Thank you in advance.

**Comment by mwizeman** [comment]
I just merged in a pull request (#1217) that should fix this issue. Please pull the latest master code and let me know if it doesn't fix the problem. Thanks!
