### ISSUE TITLE
Dose Visallo support data copy and paste between workspaces?

### ISSUE THREAD

**Issue by liuxiumin** [visallo/visallo#1265]
I would like to know whether visallo supports data copy and paste between workspaces? Where is the code file? Our project is based on visallo development, currently does not support this feature.

**Comment by sfeng88** [comment]
Visallo supports copying and pasting unpublished and published data between different graph products and supports copy and paste between cases if the data is published. 

We've tested this against the latest master code base. Are you on the latest code?

**Comment by liuxiumin** [comment]
The version of our project is 1.1-SANPSHOT, not the latest code.

**Comment by sfeng88** [comment]
1.1-SNAPSHOT is very outdated code (more than a year old) and not a version that we are supporting.

Closing this issue. Please update to a newer version and reopen an issue if you are still seeing issues.
