### ISSUE TITLE
Dose visallo support creating multiple canvas in a workspace?

### ISSUE THREAD

**Issue by liuxiumin** [visallo/visallo#1266]
I would like to know if visallo supports creating multiple canvas in a workspace ? What is the code file to modify?

**Comment by sfeng88** [comment]
Visallo supports multiple work products (graphs & maps) within a case. Are you on the latest code base?

**Comment by sfeng88** [comment]
I'm assuming based on your comment on https://github.com/visallo/visallo/issues/1265, this is also based on `1.1-SNAPSHOT`.

1.1-SNAPSHOT is very outdated code (more than a year old) and not a version that we are supporting.

Closing this issue. Please update to a newer version and reopen an issue if you are still seeing issues.

**Comment by liuxiumin** [comment]
can you show me some  screenshots about  multiple work products (graphs & maps) within a case, I just wonder if visallo can support multiple canvas like this:
![image](https://user-images.githubusercontent.com/31054551/30154910-f16b0eca-93ed-11e7-8055-667f8b0d2b85.png)
If Visallo can support, we will update to the latest version.
Thank you so much, looking forward to your reply

**Comment by sfeng88** [comment]
@liuxiumin you can find examples of what the UI looks like on our website

https://visallo.com/learn/
