### ISSUE TITLE
Cannot run application

### ISSUE THREAD

**Issue by ileyd** [visallo/visallo#1323]
Hi,

Following the [Getting Started](http://docs.visallo.org/versions/master/getting-started.html) guide, I am unable to get Visallo to run.

`mvn -Dskiptests compile` returns no errors and displays `BUILD SUCCESS` in its output, however `mvn -am -pl dev/tomcat-server -P dev-tomcat-run compile` shows a number of errors.

I am using Fedora 26 and Maven 3.3.9.  I have tested this with the master branch and the 3.1.3 release.

Any help getting Visallo to work would be greatly appreciated.

[Log output for `mvn -Dskiptests compile`](https://pastebin.com/RKyYZSnf)
[Log output for `mvn -am -pl dev/tomcat-server -P dev-tomcat-run compile`](https://pastebin.com/NZmk3HhQ)

**Comment by sfeng88** [comment]
A couple of questions:

1) Do you have a `datastore` directory under `visallo`?
2) If you do have a `datastore` directory, can you send us a listing including file permissions?

**Comment by ileyd** [comment]
Sure @sfeng88 !  There is a datastore directory using both branches, and [here](https://my.mixtape.moe/gouohv.tar) is a tar archive containing the directory from the 3.1.3 release.

The permissions should be intact in the archive but if not,
```
 lunaa@sadie  ~/Development/visallo-visallo-3.1.3  ls -l datastore
total 4
drwxr-xr-x. 2 lunaa lunaa 4096 Sep 19 13:32 h2
 lunaa@sadie  ~/Development/visallo-visallo-3.1.3  ls -l datastore/h2 
total 68
-rw-r--r--. 1 lunaa lunaa 69632 Sep 19 13:32 visallo.mv.db
```

**Comment by sfeng88** [comment]
@ileyd I tried reproducing your error on a Fedora 26 with Maven 3.3.9 docker container and was unsuccessful.

Can you please delete your entire datastore directory and then run `mvn -am -pl dev/tomcat-server -P dev-tomcat-run compile`?

That command should create a datastore directory with the following directories:
<img width="405" alt="screen shot 2017-10-03 at 12 22 50 pm" src="https://user-images.githubusercontent.com/4804560/31136240-a14ccff8-a835-11e7-84ab-30125ab147aa.png">

**Comment by ileyd** [comment]
@sfeng88 Thanks!  Consistently with a fresh copy of the source, if i do not remove the datastore directory, the issue I described occurs, but if I remove it after compilation it seems to work fine.
