### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by R2D2-fwks** [visallo/visallo#1464]
Hi I am cloning the visallo repo  and the running the command 
      `mvn -am -pl dev/tomcat-server -P dev-tomcat-run compile`.

And when i look back to localhost its showing only icon.

Any way i am looking into wrong direction

**Comment by sfeng88** [comment]
Was there any errors when running the maven command? Any errors in the browser console?

**Comment by R2D2-fwks** [comment]
After checking it was a build failure from my end .
