### ISSUE TITLE
Developer guide ?

### ISSUE THREAD

**Issue by R2D2-fwks** [visallo/visallo#1467]
Hi , 

I need some developer guide with reference to files , to make changes in UI . The documentation is pretty confusing .

**Comment by sfeng88** [comment]
Can you elaborate more on what is confusing? Also, which pages of the documentation are confusing?

**Comment by R2D2-fwks** [comment]
There are parts in the documentation , which says to change in the file .But to change in which file , is not certain ,For example , i have to ingest the data in visaalo , the doc says add two line in the config file , but which config file ,Its not markdown. There are plenty of examples like this .

**Comment by sfeng88** [comment]
Can you provide links for reference or which sections of the docs you are referring to?
