### ISSUE TITLE
Error Compiling Visallo

### ISSUE THREAD

**Issue by robmullr** [visallo/visallo#1468]
mvn install -f root/pom.xml executed fine.
On Windows 10, trying to compile stock visallo using 'mvn compile'.  Getting error "Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:ins tall-node-and-yarn (install-node-and-yarn) on project visallo-core: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.2.1/yarn-v1.2.1.tar.gz:  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
The path to yarn is correct and reachable via browser.

**Comment by sfeng88** [comment]
are you behind a proxy?

**Comment by robmullr** [comment]
Yes, maven\conf\settings.xml contains the corporate proxy settings.
