### ISSUE TITLE
What is App in visallo?

### ISSUE THREAD

**Issue by R2D2-fwks** [visallo/visallo#1471]
Hi , 

I am pretty to new to visallo , also i have very limited knowledge of java, yet i am slightly confused about the ways of Starting the visallo . The firs way is to ` mvn -am -pl dev/tomcat-server -P dev-tomcat-run compile` run this command and the second way is to use `bin/generate-archetype-project.sh` .
What is the difference between two ? Any document regarding this

**Comment by sfeng88** [comment]
I think the best solution would be to familiarize yourself with how maven works. That is outside the scope of Visallo. You can find out more information about maven on their [website](https://maven.apache.org/). Also you can find/post general questions on our [Google Group](https://groups.google.com/forum/#!forum/visallo).

Thanks!
