### ISSUE TITLE
exception and  pages

### ISSUE THREAD

**Issue by j782070772** [visallo/visallo#426]
In PrivilegeFilter, while throw VisalloAccessDeniedException, Page does not display any excepion information, and stuck. It's not friendly to the user experience

**Comment by sfeng88** [comment]
@j782070772 Can you elaborate a little bit more about what you mean by "stuck"?

**Comment by sfeng88** [comment]
Closing this issue for now. Please reopen/submit a new issue if this problem still occurs.
