### ISSUE TITLE
What is the role of DashboardRefreshData in dashboard.js?

### ISSUE THREAD

**Issue by Samli514006030** [visallo/visallo#942]
Hello there. I updated the test dashboard refresh function, but there is no response on the page, the background has not sent data, what is the specific function of this function? Thank you

**Comment by joeybrk372** [comment]
Dashboard item components should listen for the `refreshData` event then make any needed changes including re-requesting their data. No data is sent unless the item requests new data itself. See: http://docs.visallo.org/versions/master/javascript/org.visallo.dashboard.item.html

**Comment by sfeng88** [comment]
Closing this issue. Please submit a new issue if any further discussion is needed.
